### ISSUE TITLE
학교 서버에 배포하기

### ISSUE THREAD

**Issue by kyurimki** [kyurimki/T-Tree#2]
### REQUIREMENTS: 학과 서버 + Java8 + MySQL8 + mysql-connector-java + .jar로 변환된 프로젝트 OR gradle로 빌드한 프로젝트 + α
#  
**기본적인 배포 방법과 틀은 [이전 이슈](https://github.com/kyurimki/T-Tree/issues/1)와 크게 다르지 않다.**

**Comment by kyurimki** [comment]
# 1. ROOT 권한으로 할 일
root 계정으로 해야할 일은 **1. 프로그램 설치 및 설정, 2. 포트 열기, 3. 사용자 생성** 이다.
## 1. 프로그램 설치 및 설정
### 1. java 설치
**1. 설치**
`dnf install java-1.8.0-openjdk-devel.x86_64` -> `y`

**2. 버전 확인**
`java -version`
=> openjdk version "1.8.0_282"
    OpenJDK Runtime Environment (build 1.8.0_282-b08)
    OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
~Gradle에서 오류 나서 확인하니까 자바가 업데이트 된 것 같다. 버전이 바뀌었다.~
     ~openjdk version "1.8.0_275"~
     ~OpenJDK Runtime Environment (build 1.8.0_275-b01)~
     ~OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)~

**3. 테스트 코드 실행**
```
public class HelloWorld {
        public static void main(String args[]) {
                System.out.println("Hello World!");
        }
}
```
`javac HelloWorld.java` -> `java HelloWorld`로 실행해서 `Hello World!` 실행되는지 확인

**4. 환경변수 설정**
`vi /etc/profile`로 환경변수 설정하기 -> `i`로 INSERT 모드 진입
```
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-1.el8_3.x86_64
export PATH=$PATH:JAVA_HOME/bin
```
-> `:wq`로 저장하고 나와서 `source /etc/profile`로 재시작
-> `echo $JAVA_HOME`, `echo $PATH` 입력해서 입력한 환경변수가 잘 출력되는지 확인하기
##
### 2. MySQL 설치
**1. 설치**
`dnf install mysql-server.x86_64` -> `y`

**2. 버전 확인**
`mysql -V`: mysql  Ver 8.0.21 for Linux on x86_64 (Source distribution)

**3. MySQL 실행**
`systemctl start mysqld(.service)` *() 안의 .service는 입력 안 해도 무방
`systemctl status mysqld`를 입력했을 때, Active: active(running) 상태여야 함. -> `:q`로 나가기
- ERROR: `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)` mysql 실행 안 됐으니 확인

**4. root 비번 설정**
`mysql -u root`로 MySQL 접속 -> `alter user 'root'@'localhost' identified with mysql_native_password by '[설정하고자 하는 비밀번호]';`
- [설정하고자 하는 비밀번호] 조건: 영어 대문자, 소문자, 숫자, 특수문자가 모두 포함된 8자리 이상
##
### 3. Gradle 설치
**1. 설치 및 압축 해제**
`wget https://services.gradle.org/distributions/gradle-6.3-bin.zip`으로 gradle 다운로드
-> `unzip -d /opt/gradle gradle-6.3-bin.zip`로 **gradle-6.3-bin.zip**의 압축 해제하고 `/opt/gradle` 디렉토리로 옮기기
- `-d`: extract files into exdir

**2. 환경변수 설정/ gradle.sh에 대한 권한 설정**
`vi /etc/profile.d/gradle.sh`로 gradle에 대한 환경변수 설정
```
export GRADLE_HOME=/opt/gradle/gradle-6.3
export PATH=${GRADLE_HOME}/bin:${PATH}
```
-> `:wq`로 저장하고 나가기
-> `chmod +x /etc/profile.d/gradle.sh`으로 **gradle.sh**에 대해 권한 열기
-> `source /etc/profile.d/gradle.sh`로 재시작
-> `echo $GRADLE_HOME`, `echo $PATH`로 설정한 환경변수 확인

**3. gradle 버전 확인**
`gradle -v`: Gradle 6.3
* 참고: [How to Install Gradle on CentOS 8](https://linuxize.com/post/how-to-install-gradle-on-centos-8/)
##
### 4. MySQL-JAVA-Connector 설치
**1. 설치 및 압축 해제**
`wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.21.tar.gz`
`ls` 명령어로 **mysql-connector-java-8.0.21.tar.gz** 파일 위치 확인 -> `tar -xvf mysql-connector-java-8.0.21.tar.gz`로 압축 해제

**2. 파일 이동**
압축 해제해 생성된 **mysql-connector-java-8.0.21** 디렉토리로 이동`cd mysql-connector-java-8.0.21`
-> `mv mysql-connector-java-8.0.21.jar $JAVA_HOME/lib`로 **mysql-connector-java-8.0.21.jar** 파일 위치 이동

**3. 환경변수 설정**
`vi /etc/profile`으로 환경 변수 설정 -> `i`로 INSERT 모드 진입
-> `export CLASSPATH=.:$JAVA_HOME/lib/mysql-connector-java-8.0.21.jar` 추가
-> `:wq`로 저장하고 나와서 `source /etc/profile`로 재시작
-> `echo $CLASSPATH` 입력해서 입력한 환경변수가 잘 출력되는지 확인하기

**4. 테스트 코드 실행**
Java와 MySQL의 연결이 원활하게 되는지 확인하기 위해 테스트 코드를 생성해 실행한다.
`vi CheckMySQL.java` -> `i`로 INSERT 모드 진입 후 입력
```
**CheckMySQL.java**
import java.sql.*;

public class CheckMySQL {
	public static void main(String[] args) {
		Connection conn = null;
		String mysql = "jdbc:mysql://localhost:3306/ttree";
		String id = "root";
		String pw = "[MySQL 비밀번호]";

		try { 
			Class.forName("com.mysql.cj.jdbc.Driver");
			System.out.println("Driver OK!!");
			conn = DriverManager.getConnection(mysql, id, pw);
			System.out.println("Conn OK!");
		} catch (Exception e){
			System.out.println("ERROR!");
			e.printStackTrace();
		}
	}
}
```
-> `:wq`로 저장 후 나오기 -> `javac CheckMySQL.java`로 컴파일 -> `java CheckMySQL`로 실행: `Driver OK!!`와 `Conn OK!`이 출력되면 정상 수행

ERROR: Timezone Error 발생
```
java.sql.SQLException: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at CheckMySQL.main(CheckMySQL.java:13)
Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:132)
	at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2120)
	at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2143)
	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1310)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:967)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
	... 6 more
```
해결방법: MySQL 접속
-> `select @@global.time_zone, @@session.time_zone;`을 입력하면 **SYSTEM**으로 출력되는지 확인
-> 서울(KST)의 시간대인 `SET GLOBAL time_zone='+09:00';`, `SET time_zone='+09:00';`  입력
- ` SET GLOBAL time_zone='Asia/Seoul';` 입력 시 `ERROR 1298 (HY000): Unknown or incorrect time zone: 'Asia/Seoul'` 발생하므로 위와 같이 입력
##
### 5. nginx 설치
**1. 설치**
`dnf install nginx` -> `y`

**2. nginx 실행**
`systemctl start nginx`로 실행
- `systemctl status nginx`에서 Active: active(running)인지 확인

**3. 설정**
`vi /etc/nginx/nginx.conf`에서 코드 추가
**3-1. nginx와 spring boot(8080 포트) 연결**
```
```
**3-2. nginx 실행**
`systemctl restart nginx`로 nginx 실행 시작
- `systemctl status nginx` 했을 때 상태가 Active: active (running)인지 확인
-> 브라우저에서 IP 주소/DNS 주소를 입력했을 때 (연결된 게 없어서 뜨는 오류 페이지더라도) 접속이 가능해야 함.

**3-3. nginx ERROR LOG**
`tail -f /var/log/nginx/error.log`로 에러 로그 파일에서 마지막 10줄 출력
- `vi`를 사용할 수도 있지만, 로그를 수정하는 것이 아니기 때문에 `tail` 명령어를 사용
* 참고: [[Nginx] 에러로그 확인 법](https://annajinee.tistory.com/17)

**3-4. nginx에서 client_max_body_size: 413 Request Entity Too Large**
ERROR: 413 Request Entity Too Large
nginx가 한 번의 request에 처리할 수 있는 기본값은 1M인데, 졸업프로젝트 관리 시스템에서 게시글 하나에 파일을 여러 개 업로드 해야 하기 때문에 처리 가능 용량을 늘려야 할 필요가 있다.
```
http {
    client_max_body_size 2048M;
    ....
}
```
소스코드 파일에 따라서는 1GB가 넘는 경우도 있어서, 2GB(=2048MB)까지 허용하였다.
- `systemctl reload nginx`로 업데이트 된 요소 반영
* 참고: [[nginx] 413 Request Entity Too Large 오류](https://blog.leocat.kr/notes/2020/04/21/nginx-413-request-entity-too-large)
##
### 6. git 설치
`git clone`을 위해 git을 설치해야 한다. -> `dnf install git` -> `y`
#
## 2. 포트 설정
Spring Boot가 실행될 때 사용되는 포트인 8080 포트를 열기 위해서 설정이 필요하다. 이를 위해 firewall-cmd를 이용한다.
`firewall-cmd --zone=public --permanent --add-service=http`
`firewall-cmd --permanent --zone=public --add-port=8080/tcp`
`firewall-cmd --reload`
#
## 3. 사용자 ttreeUser 생성 후 설정
보안 측면에서 root 사용자로 졸업프로젝트 관리 시스템을 실행시키는 것보다 새로운 사용자를 생성하는 편이 더 안전하기 때문에 ttreeUser를 생성해서 실행시키고자 한다.
**1. ttreeUser 생성**
`adduser ttreeUser`로 ttreeUser를 생성한다.

**2. nginx 설정**
ttreeUser에서 nginx를 이용해 졸업프로젝트 관리 시스템을 실행할 것이기 때문에 user를 바꿔야 한다.
`vi /etc/nginx/nginx.conf`로 접속 -> `i`로 INSERT 모드 진입
-> `user nginx;`를 `user ttreeUser`로 바꿔준다.
-> `systemctl reload nginx`로 nginx 재시작

**Comment by kyurimki** [comment]
# 2. ttreeUser 권한으로 할 일
ttreeUser가 해야 되는 일은 **1. 프로젝트를 받아와서, 2. 빌드 해서, 3. 실행**시키는 일이다. 이를 위해 사용자를 `su ttreeUser`로 전환한다.
## 0. 비밀번호 설정하기
`passwd`로 ttreeUser에 대한 비밀번호 설정
#
## 1. 프로젝트 clone
**1. 프로젝트 clone**
`git clone https://github.com/kyurimki/T-Tree.git`으로 프로젝트 clone

**2. application.properties 생성**
#
## 2. 프로젝트 build
**1. gradlew에 권한 부여**
`cd ~/T-Tree/ttreeGradle`로 이동 -> **gradlew**가 있는 디렉토리에서 `chmod 777 gradlew`로 **gradlew**에 대해 권한 부여
**2. build**
`./gradlew build`로 프로젝트 빌드하기
#
## 3. 프로젝트 실행
빌드 완료(BUILD SUCCESSFUL) 후`cd build/libs`로 이동
-> `java -jar ttreeGradle-0.0.1-SNAPSHOT.jar` 하면 스프링부트 수행
-> http://[IP 주소/DNS 주소]로 접속 확인하기
(:8080을 붙여도 접속은 가능하나, nginx를 거치지 않고 실행되는 것이다.)

NGINX ERROR: 연결이 되었는데도 불구하고, 사이트에 접속할 수 없거나, 특정 파일만 안 뜨는 Permission Denied가 발생(error log 확인)
1. SELinux 설정
`chcon -R -t httpd_sys_content_t /home/ttreeUser`
- `-R` 옵션으로 ttreeUser 하위 디렉토리에 모두 적용한다.
2. **/home/ttreeUser/T-Tree/ttreeGradle** 디렉토리의 권한을 root에서 ttreeUser로 바꿔준다.
```
chmod -R 755 ttreeGradle
chown -R ttreeUser:ttreeUser ttreeGradle
```
- 참고: [Nginx 403 (13: Permission denied) 에러 해결](https://ganbarujoy.tistory.com/113)
- 참고: [/var/lib/nginx/ Permission Denied](https://github.com/dockerfile/nginx/issues/4)
